using System.Collections;
using System.Globalization;
using System.Resources;

namespace ProxyManager.Standalone.Localization;

// Hand-written accessor so command-line builds do not depend on the Visual Studio
// resx code generator. Properties are public for XAML x:Static references.
public static class Strings
{
    private static readonly ResourceManager Manager = new(
        "ProxyManager.Standalone.Localization.Strings",
        typeof(Strings).Assembly);

    public static string SettingsRuntimeTitle => GetString(nameof(SettingsRuntimeTitle));
    public static string SettingsRuntimeIntro => GetString(nameof(SettingsRuntimeIntro));
    public static string SettingsRuntimePathTooltip => GetString(nameof(SettingsRuntimePathTooltip));
    public static string SettingsRuntimeBrowse => GetString(nameof(SettingsRuntimeBrowse));
    public static string SettingsRuntimeRecheck => GetString(nameof(SettingsRuntimeRecheck));
    public static string SettingsRuntimeClear => GetString(nameof(SettingsRuntimeClear));
    public static string SettingsRuntimeVersionUnchecked => GetString(nameof(SettingsRuntimeVersionUnchecked));
    public static string SettingsRuntimeChecking => GetString(nameof(SettingsRuntimeChecking));
    public static string SettingsAiHealthTitle => GetString(nameof(SettingsAiHealthTitle));
    public static string SettingsAiHealthIntro => GetString(nameof(SettingsAiHealthIntro));
    public static string SettingsAiHealthRun => GetString(nameof(SettingsAiHealthRun));
    public static string SettingsAiHealthNotRun => GetString(nameof(SettingsAiHealthNotRun));
    public static string SettingsProxyTitle => GetString(nameof(SettingsProxyTitle));
    public static string SettingsProxyIntro => GetString(nameof(SettingsProxyIntro));
    public static string SettingsProxyType => GetString(nameof(SettingsProxyType));
    public static string SettingsProxyHost => GetString(nameof(SettingsProxyHost));
    public static string SettingsProxyPort => GetString(nameof(SettingsProxyPort));
    public static string SettingsProxyUsername => GetString(nameof(SettingsProxyUsername));
    public static string SettingsProxyPassword => GetString(nameof(SettingsProxyPassword));
    public static string SettingsProxySave => GetString(nameof(SettingsProxySave));
    public static string SettingsProxyTest => GetString(nameof(SettingsProxyTest));
    public static string SettingsProxyTestHint => GetString(nameof(SettingsProxyTestHint));
    public static string SettingsLanguageTitle => GetString(nameof(SettingsLanguageTitle));
    public static string SettingsLanguageIntro => GetString(nameof(SettingsLanguageIntro));
    public static string SettingsLanguageChinese => GetString(nameof(SettingsLanguageChinese));
    public static string SettingsLanguageEnglish => GetString(nameof(SettingsLanguageEnglish));
    public static string SettingsLanguageFollowSystem => GetString(nameof(SettingsLanguageFollowSystem));
    public static string SettingsLanguageRestartHint => GetString(nameof(SettingsLanguageRestartHint));

    public static string WindowTitle => GetString(nameof(WindowTitle));
    public static string NavItemRules => GetString(nameof(NavItemRules));
    public static string NavItemPolicy => GetString(nameof(NavItemPolicy));
    public static string NavItemRouteSimulator => GetString(nameof(NavItemRouteSimulator));
    public static string NavItemAi => GetString(nameof(NavItemAi));
    public static string NavItemMonitor => GetString(nameof(NavItemMonitor));
    public static string NavItemProcess => GetString(nameof(NavItemProcess));
    public static string NavItemSettings => GetString(nameof(NavItemSettings));
    public static string NavItemAbout => GetString(nameof(NavItemAbout));
    public static string SidebarVersion => GetString(nameof(SidebarVersion));
    public static string StatusFooterLabel => GetString(nameof(StatusFooterLabel));
    public static string StatusFooterInitial => GetString(nameof(StatusFooterInitial));
    public static string ModeDirectLabel => GetString(nameof(ModeDirectLabel));
    public static string ModeProxyLabel => GetString(nameof(ModeProxyLabel));
    public static string WindowMinimizeName => GetString(nameof(WindowMinimizeName));
    public static string WindowMaximizeName => GetString(nameof(WindowMaximizeName));
    public static string WindowCloseName => GetString(nameof(WindowCloseName));
    public static string PageTitleRules => GetString(nameof(PageTitleRules));
    public static string PageTitleAi => GetString(nameof(PageTitleAi));
    public static string PageTitlePolicy => GetString(nameof(PageTitlePolicy));
    public static string PageTitleRouteSimulator => GetString(nameof(PageTitleRouteSimulator));
    public static string PageTitleMonitor => GetString(nameof(PageTitleMonitor));
    public static string PageTitleProcess => GetString(nameof(PageTitleProcess));
    public static string PageTitleSettings => GetString(nameof(PageTitleSettings));
    public static string PageTitleAbout => GetString(nameof(PageTitleAbout));
    public static string PageSubtitleRules => GetString(nameof(PageSubtitleRules));
    public static string PageSubtitleAi => GetString(nameof(PageSubtitleAi));
    public static string PageSubtitlePolicy => GetString(nameof(PageSubtitlePolicy));
    public static string PageSubtitleRouteSimulator => GetString(nameof(PageSubtitleRouteSimulator));
    public static string PageSubtitleMonitor => GetString(nameof(PageSubtitleMonitor));
    public static string PageSubtitleProcess => GetString(nameof(PageSubtitleProcess));
    public static string PageSubtitleSettings => GetString(nameof(PageSubtitleSettings));
    public static string PageSubtitleAbout => GetString(nameof(PageSubtitleAbout));
    public static string MenuToggleEnabled => GetString(nameof(MenuToggleEnabled));
    public static string MenuForceProxy => GetString(nameof(MenuForceProxy));
    public static string MenuForceDirect => GetString(nameof(MenuForceDirect));
    public static string MenuForceBlock => GetString(nameof(MenuForceBlock));
    public static string MenuMoveUp => GetString(nameof(MenuMoveUp));
    public static string MenuMoveDown => GetString(nameof(MenuMoveDown));
    public static string MenuDelete => GetString(nameof(MenuDelete));
    public static string AboutTagline => GetString(nameof(AboutTagline));
    public static string AboutFeaturesTitle => GetString(nameof(AboutFeaturesTitle));
    public static string AboutFeature1 => GetString(nameof(AboutFeature1));
    public static string AboutFeature2 => GetString(nameof(AboutFeature2));
    public static string AboutFeature3 => GetString(nameof(AboutFeature3));
    public static string AboutFeature4 => GetString(nameof(AboutFeature4));
    public static string AboutFeature5 => GetString(nameof(AboutFeature5));
    public static string AboutFeature6 => GetString(nameof(AboutFeature6));
    public static string AboutFeature7 => GetString(nameof(AboutFeature7));
    public static string AboutFeature8 => GetString(nameof(AboutFeature8));
    public static string AboutFooter => GetString(nameof(AboutFooter));

    public static string RecoveryBannerTitle => GetString(nameof(RecoveryBannerTitle));
    public static string RecoveryOpenFolder => GetString(nameof(RecoveryOpenFolder));
    public static string RecoveryImport => GetString(nameof(RecoveryImport));
    public static string RecoveryReset => GetString(nameof(RecoveryReset));
    public static string RulesSearchPlaceholder => GetString(nameof(RulesSearchPlaceholder));
    public static string RulesAdd => GetString(nameof(RulesAdd));
    public static string RulesImport => GetString(nameof(RulesImport));
    public static string RulesExport => GetString(nameof(RulesExport));
    public static string RulesClear => GetString(nameof(RulesClear));
    public static string RulesHeaderApp => GetString(nameof(RulesHeaderApp));
    public static string RulesHeaderMode => GetString(nameof(RulesHeaderMode));
    public static string RulesHeaderStatus => GetString(nameof(RulesHeaderStatus));
    public static string RulesHeaderTime => GetString(nameof(RulesHeaderTime));
    public static string RulesRowMenuHint => GetString(nameof(RulesRowMenuHint));
    public static string RulesEmptyPrimary => GetString(nameof(RulesEmptyPrimary));
    public static string RulesEmptySecondary => GetString(nameof(RulesEmptySecondary));
    public static string RulesDropOverlay => GetString(nameof(RulesDropOverlay));
    public static string AiProviderLabel => GetString(nameof(AiProviderLabel));
    public static string ModelLabel => GetString(nameof(ModelLabel));
    public static string RefreshModelsLabel => GetString(nameof(RefreshModelsLabel));
    public static string AiPrivacyInitial => GetString(nameof(AiPrivacyInitial));
    public static string AiIntentTitle => GetString(nameof(AiIntentTitle));
    public static string AiIntentExample => GetString(nameof(AiIntentExample));
    public static string AiCancelGeneration => GetString(nameof(AiCancelGeneration));
    public static string AiGenerateLabel => GetString(nameof(AiGenerateLabel));
    public static string AiDraftHeaderTitle => GetString(nameof(AiDraftHeaderTitle));
    public static string AiDraftEditHint => GetString(nameof(AiDraftEditHint));
    public static string AiColProcess => GetString(nameof(AiColProcess));
    public static string ActionLabel => GetString(nameof(ActionLabel));
    public static string AiColDomain => GetString(nameof(AiColDomain));
    public static string AiColIp => GetString(nameof(AiColIp));
    public static string PortLabel => GetString(nameof(PortLabel));
    public static string AiColProtocol => GetString(nameof(AiColProtocol));
    public static string AiColRationale => GetString(nameof(AiColRationale));
    public static string AiColConfidence => GetString(nameof(AiColConfidence));
    public static string AiStatusInitial => GetString(nameof(AiStatusInitial));
    public static string AiAcceptLabel => GetString(nameof(AiAcceptLabel));
    public static string PolicyStatActive => GetString(nameof(PolicyStatActive));
    public static string PolicyStatCritical => GetString(nameof(PolicyStatCritical));
    public static string PolicyStatWarning => GetString(nameof(PolicyStatWarning));
    public static string PolicyStatDisabled => GetString(nameof(PolicyStatDisabled));
    public static string PolicyReanalyze => GetString(nameof(PolicyReanalyze));
    public static string PolicyLocate => GetString(nameof(PolicyLocate));
    public static string PolicyPrivacyNote => GetString(nameof(PolicyPrivacyNote));
    public static string PolicyFindingsTitle => GetString(nameof(PolicyFindingsTitle));
    public static string PolicyColSeverity => GetString(nameof(PolicyColSeverity));
    public static string PolicyColCode => GetString(nameof(PolicyColCode));
    public static string PolicyColIssue => GetString(nameof(PolicyColIssue));
    public static string PolicyColAffected => GetString(nameof(PolicyColAffected));
    public static string PolicyColGuidance => GetString(nameof(PolicyColGuidance));
    public static string PolicyEmpty => GetString(nameof(PolicyEmpty));
    public static string PolicyAiSummaryTitle => GetString(nameof(PolicyAiSummaryTitle));
    public static string PolicyAiSummaryInitial => GetString(nameof(PolicyAiSummaryInitial));
    public static string PolicyAdviceTitle => GetString(nameof(PolicyAdviceTitle));
    public static string PolicyAdviceColExplanation => GetString(nameof(PolicyAdviceColExplanation));
    public static string PolicyAdviceColNext => GetString(nameof(PolicyAdviceColNext));
    public static string PolicyStatusInitial => GetString(nameof(PolicyStatusInitial));
    public static string PolicyCancelExplanation => GetString(nameof(PolicyCancelExplanation));
    public static string PolicyExplain => GetString(nameof(PolicyExplain));
    public static string RouteBannerTitle => GetString(nameof(RouteBannerTitle));
    public static string RouteBannerBody => GetString(nameof(RouteBannerBody));
    public static string RouteProcessLabel => GetString(nameof(RouteProcessLabel));
    public static string RouteProcessTooltip => GetString(nameof(RouteProcessTooltip));
    public static string RouteDestinationKindLabel => GetString(nameof(RouteDestinationKindLabel));
    public static string RouteDestinationDomain => GetString(nameof(RouteDestinationDomain));
    public static string RouteDestinationIp => GetString(nameof(RouteDestinationIp));
    public static string RouteDestinationLabelDomain => GetString(nameof(RouteDestinationLabelDomain));
    public static string RouteDestinationTooltip => GetString(nameof(RouteDestinationTooltip));
    public static string RouteTransportLabel => GetString(nameof(RouteTransportLabel));
    public static string RouteSimulate => GetString(nameof(RouteSimulate));
    public static string RouteSimulateName => GetString(nameof(RouteSimulateName));
    public static string RouteResultTitle => GetString(nameof(RouteResultTitle));
    public static string RouteBadgeInitial => GetString(nameof(RouteBadgeInitial));
    public static string RouteSourceLabel => GetString(nameof(RouteSourceLabel));
    public static string RouteSourceInitial => GetString(nameof(RouteSourceInitial));
    public static string RouteReasonLabel => GetString(nameof(RouteReasonLabel));
    public static string RouteReasonInitial => GetString(nameof(RouteReasonInitial));
    public static string RouteSnapshotLabel => GetString(nameof(RouteSnapshotLabel));
    public static string RouteSnapshotInitial => GetString(nameof(RouteSnapshotInitial));
    public static string RouteLocate => GetString(nameof(RouteLocate));
    public static string RouteLocateName => GetString(nameof(RouteLocateName));
    public static string RouteTraceTitle => GetString(nameof(RouteTraceTitle));
    public static string RouteTraceColOrder => GetString(nameof(RouteTraceColOrder));
    public static string RouteTraceColRule => GetString(nameof(RouteTraceColRule));
    public static string RouteTraceColConclusion => GetString(nameof(RouteTraceColConclusion));
    public static string RouteTraceColReason => GetString(nameof(RouteTraceColReason));
    public static string RouteTraceEmpty => GetString(nameof(RouteTraceEmpty));
    public static string RouteStatusInitial => GetString(nameof(RouteStatusInitial));
    public static string MonitorTitle => GetString(nameof(MonitorTitle));
    public static string MonitorClear => GetString(nameof(MonitorClear));
    public static string MonitorColTime => GetString(nameof(MonitorColTime));
    public static string MonitorColMessage => GetString(nameof(MonitorColMessage));
    public static string ProcessTitle => GetString(nameof(ProcessTitle));
    public static string ProcessRefresh => GetString(nameof(ProcessRefresh));
    public static string ProcessColPid => GetString(nameof(ProcessColPid));
    public static string ProcessColName => GetString(nameof(ProcessColName));
    public static string ProcessColPath => GetString(nameof(ProcessColPath));
    public static string ProcessColStatus => GetString(nameof(ProcessColStatus));

    public static string ModeProxyText => GetString(nameof(ModeProxyText));
    public static string ModeDirectText => GetString(nameof(ModeDirectText));
    public static string ModeBlockText => GetString(nameof(ModeBlockText));
    public static string RuleStatusEnabled => GetString(nameof(RuleStatusEnabled));
    public static string RuleStatusDisabled => GetString(nameof(RuleStatusDisabled));
    public static string RuleConditionHostsPrefix => GetString(nameof(RuleConditionHostsPrefix));
    public static string RuleConditionIpPrefix => GetString(nameof(RuleConditionIpPrefix));
    public static string RuleConditionPortsPrefix => GetString(nameof(RuleConditionPortsPrefix));
    public static string RuleConditionAll => GetString(nameof(RuleConditionAll));
    public static string ServerStatusEnabled => GetString(nameof(ServerStatusEnabled));
    public static string ServerStatusDisabled => GetString(nameof(ServerStatusDisabled));
    public static string CountProxyFormat => GetString(nameof(CountProxyFormat));
    public static string CountDirectFormat => GetString(nameof(CountDirectFormat));
    public static string CountBlockFormat => GetString(nameof(CountBlockFormat));
    public static string CountRulesFormat => GetString(nameof(CountRulesFormat));
    public static string CountFindingsFormat => GetString(nameof(CountFindingsFormat));
    public static string CountTraceFormat => GetString(nameof(CountTraceFormat));
    public static string CountProcessesFormat => GetString(nameof(CountProcessesFormat));
    public static string VersionPrefix => GetString(nameof(VersionPrefix));
    public static string SeverityCritical => GetString(nameof(SeverityCritical));
    public static string SeverityWarning => GetString(nameof(SeverityWarning));
    public static string SeverityInfo => GetString(nameof(SeverityInfo));
    public static string TraceVerdictMatch => GetString(nameof(TraceVerdictMatch));
    public static string TraceVerdictMiss => GetString(nameof(TraceVerdictMiss));
    public static string TraceVerdictIndeterminate => GetString(nameof(TraceVerdictIndeterminate));
    public static string RouteBadgeMatched => GetString(nameof(RouteBadgeMatched));
    public static string RouteBadgeFallback => GetString(nameof(RouteBadgeFallback));
    public static string RouteBadgeInvalidQuery => GetString(nameof(RouteBadgeInvalidQuery));
    public static string RouteBadgeInvalidPolicy => GetString(nameof(RouteBadgeInvalidPolicy));
    public static string RouteBadgeNoConclusion => GetString(nameof(RouteBadgeNoConclusion));
    public static string RouteActionUnproven => GetString(nameof(RouteActionUnproven));
    public static string AnalyzingText => GetString(nameof(AnalyzingText));
    public static string VersionUnrecognized => GetString(nameof(VersionUnrecognized));
    public static string VersionCheckBlocked => GetString(nameof(VersionCheckBlocked));

    public static string GetString(string name) => Manager.GetString(name) ?? string.Empty;

    public static IReadOnlySet<string> GetKeySet(CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(culture);
        // GetResourceSet hands out the manager's cached instance; disposing it here
        // would poison the cache for every later GetString call.
        var resourceSet = Manager.GetResourceSet(culture, createIfNotExists: true, tryParents: false);
        if (resourceSet == null) return new HashSet<string>();
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (DictionaryEntry entry in resourceSet)
            if (entry.Key is string key)
                keys.Add(key);
        return keys;
    }
}
